#!/usr/bin/env python3
"""Convert assets/fortunes.md into a C string-array include.

Extracts numbered entries, transliterates typographic unicode to ASCII
(the builtin debug font is ASCII-only), and escapes rdpq_text's special
characters ($ and ^) so a fortune can never trip the escape parser.
"""
import re
import sys

UNICODE_MAP = {
    "—": "-", "–": "-",            # em/en dash
    "‘": "'", "’": "'",            # smart single quotes
    "“": '"', "”": '"',            # smart double quotes
    "…": "...",
    " ": " ",
}

def sanitize(s: str) -> str | None:
    for k, v in UNICODE_MAP.items():
        s = s.replace(k, v)
    s = "".join(ch for ch in s if 32 <= ord(ch) < 127)
    if "$" in s or "^" in s:
        # rdpq_text escape chars; escaping them ("$$"/"^^") would break
        # the marquee's byte==char==8px substring windowing, so skip.
        print(f"gen_fortunes: WARNING, skipping entry with $/^: {s[:50]!r}",
              file=sys.stderr)
        return None
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    return s.strip()

def main() -> None:
    src, dst = sys.argv[1], sys.argv[2]
    entries = []
    with open(src, encoding="utf-8") as f:
        for line in f:
            m = re.match(r"^\d+\.\s+(.*\S)\s*$", line)
            if m:
                s = sanitize(m.group(1))
                if s:
                    entries.append(s)
    if not entries:
        sys.exit(f"no numbered entries found in {src}")
    with open(dst, "w", encoding="ascii") as f:
        f.write("/* Generated by tools/gen_fortunes.py from %s -- do not edit. */\n"
                % src)
        for e in entries:
            f.write('"%s",\n' % e)
    print(f"gen_fortunes: {len(entries)} entries -> {dst}")

if __name__ == "__main__":
    main()
